# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssfeed',
            name='id',
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
