# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20160822_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='content_file',
            field=models.CharField(default='articles/default_content.txt', max_length=1000),
        ),
    ]
