# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_rssfeed_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
