# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20160824_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='sentiment_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
