# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsgroup',
            old_name='asset_Id',
            new_name='asset_id',
        ),
        migrations.RemoveField(
            model_name='news',
            name='group_id',
        ),
        migrations.AddField(
            model_name='news',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robo_app.NewsGroup'),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
