# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo_app', '0003_auto_20161025_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
